import type { CalculatorKind } from "@/lib/calculatorKind";

/**
 * 제목 매칭이 빠진 카탈로그 항목을 기존 계산기 종류에 연결합니다.
 */
export const SLUG_KIND_FALLBACK: Partial<Record<string, CalculatorKind>> = {
  // 직장
  "job-006": "unemploymentBenefit",
  "job-007": "compoundSavings",
  "job-016": "bonusTax",
  "job-017": "incomeTaxMonthly",
  "job-022": "ageInternational",
  "job-023": "maternityPay",
  "job-024": "parentalLeavePay",
  "job-025": "dateDiffDetailed",
  "job-026": "eitcPay",
  // 건강
  "health-005": "ffmi",
  "health-006": "proteinIntake",
  "health-009": "standardWeight",
  "health-014": "ffmi",
  "health-015": "oneRm",
  "health-018": "heightPercentile",
  "health-022": "caffeineIntake",
  // 학교
  "school-002": "schoolRank",
  "school-004": "polynomialFactor",
  "school-005": "gpaCalc",
  "school-006": "modulo",
  "school-007": "gaussianElimination",
  "school-014": "confidenceInterval",
  "school-015": "speechTime",
  "school-016": "percentChange",
  "school-017": "pValueZ",
  "school-018": "weightedAvg",
  "school-019": "correlation",
  "school-022": "percentChange",
  // 금융
  "finance-002": "compoundSavings",
  "finance-003": "overspendRatio",
  "finance-007": "jeonseVsMonthly",
  "finance-008": "discount",
  "finance-014": "margin",
  "finance-015": "straightLineDepreciation",
  "finance-016": "ebitdaCalc",
  "finance-023": "aprCalc",
  "finance-027": "subscriptionScore",
  // 단위
  "unit-004": "gallonLiter",
  "unit-005": "buildingCoverage",
  "unit-006": "floorAreaRatio",
  "unit-007": "ppmConcentration",
  "unit-008": "dmsConvert",
  "unit-009": "slopeAngle",
  "unit-010": "perimeter",
  "unit-011": "radianConvert",
  "unit-012": "cubicMeter",
  "unit-013": "densityCalc",
  "unit-016": "wattCalc",
  "unit-017": "decibelCalc",
  "unit-018": "unitConvert",
  // 일상
  "daily-002": "withholdingTax",
  "daily-004": "lunarCalendar",
  "daily-009": "dday",
  "daily-011": "dday",
  "daily-012": "onlineTimer",
  "daily-013": "carTax",
  // 개발
  "dev-008": "qrCodeGen",
  "dev-011": "colorHexRgb",
  // 게임
  "game-002": "fifaFee",
  "game-003": "percentChange",
  "game-007": "rouletteSpinner",
  // 군대
  "military-001": "compoundSavings",
  "military-002": "airForceWeightedScore",
  "military-003": "marineClassEstimate",
  "military-004": "dischargeDateEstimate",
  // 스포츠
  "sports-003": "vdotEstimate",
  "sports-005": "bowlingPinSum",
  "sports-006": "curlingEndSum",
};
